## Embedding a Bokeh server in a Notebook

This notebook shows how a Bokeh server application can be embedded inside a Jupyter notebook.

In [1]:
import yaml
import datetime as dt

import pandas as pd
import numpy as np

from bokeh.layouts import column
from bokeh.models import ColumnDataSource, Slider, LabelSet
from bokeh.plotting import figure
from bokeh.themes import Theme
from bokeh.palettes import Spectral4
from bokeh.io import show, output_notebook

from bokeh.sampledata.sea_surface_temperature import sea_surface_temperature

output_notebook()

In [2]:
## IMPORT IO TRACES AND CREATE TWO DATAFRAMES

io_traces = None
with open("io_operations.yml", "r", encoding="utf-8") as traces:
    io_traces = yaml.load(traces, Loader=yaml.SafeLoader)

job_columns = [
    "job_id",
    "job_uid"
    "job_status", 
    "job_submit_ts", 
    "job_end_ts", 
    "job_duration",
    "origin_runtime",
    "origin_read_bytes",
    "origin_written_bytes",
    "origin_core_used",
    "origin_mpi_procs",
    "job_sleep_time",
]

# Not all columns are used by every type of action...
action_columns = [
    "act_name",
    "act_type",
    "act_status",
    "act_start_ts",
    "act_end_ts",
    "act_duration",
    "src_storage_service",
    "src_storage_server",
    "src_storage_disk",
    "src_file_path",
    "src_file_name",
    "src_file_size_bytes",
    "dst_storage_service",
    "dst_storage_server",
    "dst_storage_disk",
    "dst_file_path",
    "dst_file_name",
    "dst_file_size_bytes",
    "parent_job_id",
]

# DATAFRAME WITH JOBS ONLY
jobs = pd.DataFrame(io_traces, columns=job_columns)



# Merge all actions into a second DataFrame, with new "parent_job_id" field associated to each one.
action_list = []
for trace in io_traces:
    local_actions = trace["job_actions"]
    for l_act in local_actions:
        l_act["parent_job_id"] = trace["job_id"]
        if not "src_storage_service" in l_act:
            l_act["src_storage_service"] = "NA"
            l_act["src_storage_server"] = "NA"
            l_act["src_storage_disk"] = "NA"
            l_act["src_file_path"] = "NA"
            l_act["src_file_name"] = "NA"
            l_act["src_file_size_bytes"] = 0
        if not "dst_storage_service" in l_act:
            l_act["dst_storage_service"] = "NA"
            l_act["dst_storage_server"] = "NA"
            l_act["dst_storage_disk"] = "NA"
            l_act["dst_file_path"] = "NA"
            l_act["dst_file_name"] = "NA"
            l_act["dst_file_size_bytes"] = 0
        action_list.append(l_act)
        
# DATAFRAME WITH ACTIONS ONLY
actions = pd.DataFrame(action_list, columns=action_columns)

In [3]:
jobs = jobs.sort_values("job_submit_ts")
jobs["job_submit_td"] = jobs["job_submit_ts"].apply(pd.to_timedelta, unit="s")
jobs

,job_id,job_uidjob_status,job_submit_ts,job_end_ts,job_duration,origin_runtime,origin_read_bytes,origin_written_bytes,origin_core_used,origin_mpi_procs,job_sleep_time,job_submit_td
0,467890,NaN,1.600351e+09,1.600351e+09,280.024343,37517,4603,2730,10,65536,NaN,18522 days 13:56:56
1,467943,NaN,1.600358e+09,1.600358e+09,333.357590,86664,1816,1214,6,65024,NaN,18522 days 15:49:57
2,468394,NaN,1.600511e+09,1.600512e+09,300.024613,85519,3142,1667,8,25600,NaN,18524 days 10:26:46
3,468394,NaN,1.600511e+09,1.600512e+09,300.028722,85516,4710,1604,8,25600,NaN,18524 days 10:26:46.001265526
4,468394,NaN,1.600511e+09,1.600512e+09,333.367190,85510,3145,7320,6,12800,NaN,18524 days 10:26:46.004837990
5,468394,NaN,1.600511e+09,1.600512e+09,400.032066,85511,3145,7549,4,12800,NaN,18524 days 10:26:46.010196686
6,468490,NaN,1.600577e+09,1.600578e+09,400.026051,86722,1982,1459,4,71168,NaN,18525 days 04:48:19.010196686
7,468525,NaN,1.600635e+09,1.600635e+09,400.025761,84842,1066,1387,4,32768,NaN,18525 days 20:42:27.010196686
8,468525,NaN,1.600635e+09,1.600636e+09,1000.026857,84921,1045,1042,1,32768,NaN,18525 days 20:42:27.011462212
9,468525,NaN,1.600635e+09,1.600635e+09,600.028331,84887,1054,1050,2,32768,NaN,18525 days 20:42:27.015034676

In [4]:
actions = actions.sort_values("act_start_ts")

# Create Timedelta columns from timestamp, in order to display data with valid date range in following plots
actions["act_start_td"] = actions["act_start_ts"].apply(pd.to_timedelta, unit="s")
actions["act_end_td"] = actions["act_end_ts"].apply(pd.to_timedelta, unit="s")

print(f"# First action registered on {dt.datetime.fromtimestamp(actions['act_start_ts'].min())}")
print(f"# Last action ends on {dt.datetime.fromtimestamp(actions['act_end_ts'].max())}")

actions

# First action registered on 2020-09-17 15:56:56.004205
# Last action ends on 2020-09-20 22:59:07.037114

,act_name,act_type,act_status,act_start_ts,act_end_ts,act_duration,src_storage_service,src_storage_server,src_storage_disk,src_file_path,...,src_file_size_bytes,dst_storage_service,dst_storage_server,dst_storage_disk,dst_file_path,dst_file_name,dst_file_size_bytes,parent_job_id,act_start_td,act_end_td
0,stagingCopy_467890,FILECOPY,COMPLETED,1.600351e+09,1.600351e+09,0.003098,simple_storage_5_5018,permanent_storage,/dev/disk0,/dev/disk0/read/,...,4603,simple_storage_0_5000,capacity0,/dev/hdd0,/dev/hdd0/,input_data_file_467890,4603,467890,18522 days 13:56:56.004205227,18522 days 13:56:56.007302761
1,fRead_467890,FILEREAD,COMPLETED,1.600351e+09,1.600351e+09,0.001778,simple_storage_0_5000,capacity0,/dev/hdd0,/dev/hdd0/,...,4603,NA,NA,NA,NA,NA,0,467890,18522 days 13:56:56.007875204,18522 days 13:56:56.009653568
2,compute_467890,COMPUTE,COMPLETED,1.600351e+09,1.600351e+09,280.000000,NA,NA,NA,NA,...,0,NA,NA,NA,NA,NA,0,467890,18522 days 13:56:56.010226011,18522 days 14:01:36.010226011
3,fWrite_467890,FILEWRITE,COMPLETED,1.600351e+09,1.600351e+09,0.001752,NA,NA,NA,NA,...,0,simple_storage_0_5000,capacity0,/dev/hdd0,/dev/hdd0/,ouptut_data_file_467890,2730,467890,18522 days 14:01:36.010798454,18522 days 14:01:36.012550116
4,archiveCopy_467890,FILECOPY,COMPLETED,1.600351e+09,1.600351e+09,0.003079,simple_storage_0_5000,capacity0,/dev/hdd0,/dev/hdd0/,...,2730,simple_storage_5_5018,permanent_storage,/dev/disk0,/dev/disk0/write/,ouptut_data_file_467890,2730,467890,18522 days 14:01:36.013122559,18522 days 14:01:36.016201496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,archiveCopy_468525-6,FILECOPY,COMPLETED,1.600636e+09,1.600636e+09,0.003062,simple_storage_0_5000,capacity0,/dev/hdd0,/dev/hdd0/,...,1042,simple_storage_5_5018,permanent_storage,/dev/disk0,/dev/disk0/write/,ouptut_data_file_468525-6,1042,468525,18525 days 20:59:07.027116060,18525 days 20:59:07.030178070
77,delRF_468525-6,FILEDELETE,COMPLETED,1.600636e+09,1.600636e+09,0.001162,NA,NA,NA,NA,...,0,simple_storage_0_5000,capacity0,/dev/hdd2,/dev/hdd2/,input_data_file_468525-6,1045,468525,18525 days 20:59:07.030750513,18525 days 20:59:07.031912088
78,delERF_468525-6,FILEDELETE,COMPLETED,1.600636e+09,1.600636e+09,0.001162,NA,NA,NA,NA,...,0,simple_storage_5_5018,permanent_storage,/dev/disk0,/dev/disk0/read/,input_data_file_468525-6,1045,468525,18525 days 20:59:07.032484530,18525 days 20:59:07.033646107
79,delWF_468525-6,FILEDELETE,COMPLETED,1.600636e+09,1.600636e+09,0.001162,NA,NA,NA,NA,...,0,simple_storage_0_5000,capacity0,/dev/hdd0,/dev/hdd0/,ouptut_data_file_468525-6,1042,468525,18525 days 20:59:07.034218550,18525 days 20:59:07.035380125
80,delEWF_468525-6,FILEDELETE,COMPLETED,1.600636e+09,1.600636e+09,0.001162,NA,NA,NA,NA,...,0,simple_storage_5_5018,permanent_storage,/dev/disk0,/dev/disk0/write/,ouptut_data_file_468525-6,1042,468525,18525 days 20:59:07.035952568,18525 days 20:59:07.037114143

In [5]:
## IMPORT STORAGE SERVICE ORIENTED IO TRACES AND CREATE TWO DATAFRAMES

io_traces_storage_service = None
with open("storage_service_operations.yml", "r", encoding="utf-8") as traces:
    io_traces_storage_service = yaml.load(traces, Loader=yaml.SafeLoader)
    
ss_io_columns = [
    "ts",
    "action_type",
    "action_name",
    "storage_service",
    "disk",
    "volume_change_bytes",
    "total_allocation_server",
    "total_used_volume_bytes_server",
    "total_allocation_disk",
    "total_used_volume_bytes_disk",
]

actions_detail = pd.DataFrame(io_traces_storage_service, columns=ss_io_columns)
actions_detail = actions_detail.sort_values("ts")
actions_detail["ts"] = actions_detail["ts"].apply(pd.to_timedelta, unit="s")
actions_detail

,ts,action_type,action_name,storage_service,disk,volume_change_bytes,total_allocation_server,total_used_volume_bytes_server,total_allocation_disk,total_used_volume_bytes_disk
0,18522 days 13:56:56.007302761,FILECOPY,stagingCopy_467890,simple_storage_0_5000,/dev/hdd0,4603,1,4603,1,4603
1,18522 days 14:01:36.012550116,FILEWRITE,fWrite_467890,simple_storage_0_5000,/dev/hdd0,2730,2,7333,2,7333
2,18522 days 14:01:36.017935514,FILEDELETE,delRF_467890,simple_storage_0_5000,/dev/hdd0,4603,1,2730,1,2730
3,18522 days 14:01:36.021403551,FILEDELETE,delWF_467890,simple_storage_0_5000,/dev/hdd0,2730,0,0,0,0
4,18522 days 15:49:57.007274866,FILECOPY,stagingCopy_467943,simple_storage_0_5000,/dev/hdd1,1816,1,1816,1,1816
5,18522 days 15:55:30.345812321,FILEWRITE,fWrite_467943,simple_storage_0_5000,/dev/hdd0,1214,2,3030,1,1214
6,18522 days 15:55:30.351182461,FILEDELETE,delRF_467943,simple_storage_0_5000,/dev/hdd1,1816,1,1214,0,0
7,18522 days 15:55:30.354650497,FILEDELETE,delWF_467943,simple_storage_0_5000,/dev/hdd0,1214,0,0,0,0
8,18524 days 10:26:46.007600546,FILECOPY,stagingCopy_468394-1,simple_storage_0_5000,/dev/hdd0,3142,1,3142,1,3142
12,18524 days 10:26:46.012966633,FILECOPY,stagingCopy_468394-2,simple_storage_0_5000,/dev/ssd0,4710,1,4710,1,4710
16,18524 days 10:26:46.021578074,FILECOPY,stagingCopy_468394-3,simple_storage_1_5003,/dev/hdd0,3145,1,3145,1,3145
20,18524 days 10:26:46.025145054,FILECOPY,stagingCopy_468394-4,simple_storage_0_5000,/dev/ssd0,3145,1,3145,1,3145
9,18524 days 10:31:46.012822628,FILEWRITE,fWrite_468394-1,simple_storage_0_5000,/dev/hdd1,1667,2,4809,1,1667
10,18524 days 10:31:46.018197298,FILEDELETE,delRF_468394-1,simple_storage_0_5000,/dev/hdd0,3142,1,1667,0,0
13,18524 days 10:31:46.018197536,FILEWRITE,fWrite_468394-2,simple_storage_1_5003,/dev/hdd0,1604,1,1604,1,1604
11,18524 days 10:31:46.021673679,FILEDELETE,delWF_468394-1,simple_storage_0_5000,/dev/hdd1,1667,0,0,0,0
14,18524 days 10:31:46.023579836,FILEDELETE,delRF_468394-2,simple_storage_0_5000,/dev/ssd0,4710,0,0,0,0
15,18524 days 10:31:46.027047873,FILEDELETE,delWF_468394-2,simple_storage_1_5003,/dev/hdd0,1604,0,0,0,0
17,18524 days 10:32:19.360189915,FILEWRITE,fWrite_468394-3,simple_storage_2_5006,/dev/hdd1,7320,1,7320,1,7320
18,18524 days 10:32:19.365621090,FILEDELETE,delRF_468394-3,simple_storage_1_5003,/dev/hdd0,3145,0,0,0,0
19,18524 days 10:32:19.369089127,FILEDELETE,delWF_468394-3,simple_storage_2_5006,/dev/hdd1,7320,0,0,0,0
21,18524 days 10:33:26.030422211,FILEWRITE,fWrite_468394-4,simple_storage_0_5000,/dev/hdd2,7549,2,10694,1,7549
22,18524 days 10:33:26.035855770,FILEDELETE,delRF_468394-4,simple_storage_0_5000,/dev/ssd0,3145,1,7549,0,0
23,18524 days 10:33:26.039323807,FILEDELETE,delWF_468394-4,simple_storage_0_5000,/dev/hdd2,7549,0,0,0,0
24,18525 days 04:48:19.019259453,FILECOPY,stagingCopy_468490,simple_storage_0_5000,/dev/hdd1,1982,1,1982,1,1982
25,18525 days 04:54:59.024467707,FILEWRITE,fWrite_468490,simple_storage_1_5003,/dev/hdd0,1459,1,1459,1,1459
26,18525 days 04:54:59.029840231,FILEDELETE,delRF_468490,simple_storage_0_5000,/dev/hdd1,1982,0,0,0,0
27,18525 days 04:54:59.033308268,FILEDELETE,delWF_468490,simple_storage_1_5003,/dev/hdd0,1459,0,0,0,0
28,18525 days 20:42:27.017776489,FILECOPY,stagingCopy_468525-5,simple_storage_0_5000,/dev/hdd1,1066,1,1066,1,1066
32,18525 days 20:42:27.021348715,FILECOPY,stagingCopy_468525-6,simple_storage_0_5000,/dev/hdd2,1045,1,1045,1,1045
36,18525 days 20:42:27.026395082,FILECOPY,stagingCopy_468525-7,simple_storage_0_5000,/dev/hdd2,1054,1,1054,1,1054
29,18525 days 20:49:07.024178267,FILEWRITE,fWrite_468525-5,simple_storage_0_5000,/dev/hdd0,1387,2,2453,1,1387
30,18525 days 20:49:07.029550076,FILEDELETE,delRF_468525-5,simple_storage_0_5000,/dev/hdd1,1066,1,1387,0,0
31,18525 days 20:49:07.033018112,FILEDELETE,delWF_468525-5,simple_storage_0_5000,/dev/hdd0,1387,0,0,0,0
37,18525 days 20:52:27.031589985,FILEWRITE,fWrite_468525-7,simple_storage_1_5003,/dev/hdd3,1050,1,1050,1,1050
38,18525 days 20:52:27.036958456,FILEDELETE,delRF_468525-7,simple_storage_0_5000,/dev/hdd2,1054,0,0,0,0
39,18525 days 20:52:27.040426493,FILEDELETE,delWF_468525-7,simple_storage_1_5003,/dev/hdd3,1050,0,0,0,0
33,18525 days 20:59:07.026543617,FILEWRITE,fWrite_468525-6,simple_storage_0_5000,/dev/hdd0,1042,2,2087,1,1042
34,18525 days 20:59:07.031912088,FILEDELETE,delRF_468525-6,simple_storage_0_5000,/dev/hdd2,1045,1,1042,0,0
35,18525 days 20:59:07.035380125,FILEDELETE,delWF_468525-6,simple_storage_0_5000,/dev/hdd0,1042,0,0,0,0

In [6]:
# Get mulitple sub-dataframes, one for each storage service in use in our data
details_by_storageservice = actions_detail.groupby('storage_service', axis=0)

In [7]:
# Extract a dataframe for each type of action

copy_actions_detail = actions_detail[actions_detail["action_type"] == "FILECOPY"]
write_actions_detail = actions_detail[actions_detail["action_type"] == "FILEWRITE"]
delete_actions_detail = actions_detail[actions_detail["action_type"] == "FILEDELETE"]

In [8]:
import numpy as np
 
from bokeh.models import ColumnDataSource, RangeTool, DatetimeTickFormatter, NumeralTickFormatter
from bokeh.transform import factor_cmap, factor_mark


VERBOSE_DT_FORMATTER = DatetimeTickFormatter(days='%d/%m', hours="%d/%m - %Hh", hourmin='%H:%M', minutes = '%H:%M')
BYTE_FORMATTER = NumeralTickFormatter(format='0.0b')
TYPES = ["FILECOPY", "FILEREAD", "COMPUTE", "FILEWRITE", "FILEDELETE"]
IO_TYPES = ["FILECOPY", "FILEREAD", "FILEWRITE", "FILEDELETE"]
IO_TYPES_NO_READ = ["FILECOPY", "FILEWRITE", "FILEDELETE"]


def bkapp(doc):
    
    # General DataFrame
    df = actions.copy()
    source = ColumnDataSource(data=df)
    
    # Details DataFrame
    df_actions_details = actions_detail.copy()
    df_details_source  = ColumnDataSource(data=df_actions_details)
    
    df_copy_details = copy_actions_detail.copy()
    df_copy_source  = ColumnDataSource(data=df_copy_details)
    
    df_write_details = write_actions_detail.copy()
    df_write_source  = ColumnDataSource(data=df_write_details)
    
    df_delete_details = delete_actions_detail.copy()
    df_delete_source  = ColumnDataSource(data=df_delete_details)
    
    DT_X_RANGE = (df["act_start_td"].min() - dt.timedelta(seconds=10000), 
                  df["act_start_td"].max() + dt.timedelta(seconds=10000))

    
    # TIMELINE WITH VARIOUS METRICS
    p = figure(
        title="Cumulative R/W Volume", 
        height=300, 
        width=950, 
        tools=["xpan", "save", "reset", "box_zoom", "pan", "zoom_out"],
        x_axis_location="above",
        background_fill_color="#efefef", 
        x_range=DT_X_RANGE
    )
    
    # p.vbar(x='act_start_td', top='src_file_size_bytes', source=source , width=0.9)

    write_cumsum = df_write_details["volume_change_bytes"].cumsum()
    p.varea(x=df_write_details["ts"], 
            y1=np.zeros(write_cumsum.shape[0]), 
            y2=write_cumsum, 
            alpha=0.8, 
            color=(0, 255, 0, 0.5),
            legend_label="WRITE")
    
    copy_cumsum = df_copy_details["volume_change_bytes"].cumsum()
    p.varea(x=df_copy_details["ts"], 
            y1=np.zeros(copy_cumsum.shape[0]), 
            y2=copy_cumsum, 
            alpha=0.8, 
            color=(0, 0, 255, 0.5),
            legend_label="COPY")
        
    delete_cumsum = delete_actions_detail["volume_change_bytes"].cumsum()
    p.varea(x=df_delete_details["ts"], 
            y1=np.zeros(delete_cumsum.shape[0]), 
            y2=delete_cumsum, 
            alpha=0.8, 
            color=(255, 0, 0, 0.5),
            legend_label="DELETE")
    
    
    p.legend.click_policy="hide"
    
    #p.varea_stack(stackers=TYPES, x="ts")
    
    
    # p.line('act_start_td', 'src_file_size_bytes', source=source, line_color=(0, 128, 255, 0.5), line_width=2)
    # p.line('act_start_td', 'dst_file_size_bytes', source=source, line_color=(128, 255, 0, 0.5), line_width=2)
    p.yaxis.axis_label = 'Byte size of file'
    p.xaxis.formatter = VERBOSE_DT_FORMATTER
    p.yaxis.formatter = BYTE_FORMATTER
    
    p2 = figure(
        title="ActionTypes", 
        height=300, 
        width=950, 
        tools=["xpan", "save", "reset", "box_zoom", "pan", "zoom_out", "hover"],
        x_axis_location="above",
        background_fill_color="#efefef", 
        x_range=p.x_range, 
        # y_range=TYPES[::-1]
    )
    p2.hover.tooltips = [
        ("Action Type", "@action_type"),
        ("Bytes Copied/Written/Deleted", "@volume_change_bytes"), 
        ("Target Server", "@storage_service"),
        ("Target Disk", "@disk")
    ]
    p2.yaxis.axis_label = 'Bytes'
    p2.xaxis.formatter = VERBOSE_DT_FORMATTER
    p2.yaxis.formatter = BYTE_FORMATTER

    
    MARKERS = ['circle_y', 'circle_cross', 'circle_x']
    
    p2.scatter("ts", "volume_change_bytes", source=df_details_source,
               legend_group="action_type", fill_alpha=0.3, size=12,
               marker=factor_mark('action_type', MARKERS, IO_TYPES_NO_READ),
               color=factor_cmap('action_type', 'Category10_5', IO_TYPES_NO_READ),
               muted_color=factor_cmap('action_type', 'Category10_5', IO_TYPES_NO_READ), muted_alpha=0.2)

    labels = LabelSet(x="ts", y="volume_change_bytes", text="symbol", y_offset=20,
                  text_font_size="11px", text_color="#ffffff",
                  source=df_details_source, text_align='center')
    p2.add_layout(labels)
    
    STORAGE_SERVICES = df_actions_details["storage_service"].unique()
    
    for service, color in zip(STORAGE_SERVICES, Spectral4):
        p2.line(x="ts", 
                y="total_used_volume_bytes_server", 
                source=df_actions_details[df_actions_details["storage_service"] == service], 
                line_width=2,
                color=color, 
                alpha=0.8, 
                muted_color=color, 
                muted_alpha=0.1, 
                legend_label=service)
        
    p2.legend.click_policy="mute"
    
    
    
    
    # RANGE SELECTION    
    select = figure(title="Range selection plot",
                height=100, width=800, y_range=p.y_range, y_axis_type=None,
                tools="", toolbar_location=None, background_fill_color="#efefef")
    
    range_tool = RangeTool(x_range=p.x_range)
    range_tool.overlay.fill_color = "navy"
    range_tool.overlay.fill_alpha = 0.1

    select.line('act_start_td', 'src_file_size_bytes', source=source, line_color=(255, 128, 0, 0.5))
    select.line('act_start_td', 'dst_file_size_bytes', source=source, line_color=(128, 255, 0, 0.5))
    select.ygrid.grid_line_color = None
    select.xaxis.formatter = VERBOSE_DT_FORMATTER
    select.yaxis.formatter = BYTE_FORMATTER
    select.add_tools(range_tool)
    select.toolbar.active_multi = range_tool
    
    def callback(attr, old, new):
        if new == 0:
            data = df
        else:
            data = df
        source.data = ColumnDataSource.from_df(data)

    doc.add_root(column(p, p2, select))

    doc.theme = Theme(json=yaml.load("""
        attrs:
            figure:
                background_fill_color: "#DDDDDD"
                outline_line_color: white
                toolbar_location: above
                height: 700
                width: 1200
            Grid:
                grid_line_dash: [6, 4]
                grid_line_color: white
    """, Loader=yaml.FullLoader))

Now we can display our application using ``show``, which will automatically create an ``Application`` that wraps ``bkapp`` using ``FunctionHandler``. The end result is that the Bokeh server will call ``bkapp`` to build new documents for every new sessions that is opened.

**Note**: If the current notebook is not displayed at the default URL, you must update the `notebook_url` parameter in the comment below to match, and pass it to `show`.

In [9]:
show(bkapp) # notebook_url="http://localhost:8888"