In [1]:
import yaml
import datetime as dt

import pandas as pd
import numpy as np
import matplotlib

from bokeh.layouts import column
from bokeh.models import (ColumnDataSource, Slider, LabelSet, CategoricalColorMapper, DataTable, HoverTool, IntEditor,
                          NumberEditor, NumberFormatter, SelectEditor,
                          StringEditor, StringFormatter, TableColumn, LinearColorMapper, ContinuousColorMapper)
from bokeh.plotting import figure
from bokeh.themes import Theme
from bokeh.palettes import Spectral4, viridis, Viridis256
from bokeh.io import show, output_notebook
from bokeh.transform import jitter, factor_cmap, linear_cmap

from squarify import normalize_sizes, squarify
import colorcet as cc


output_notebook()

In [2]:
## IMPORT IO TRACES AND CREATE TWO DATAFRAMES

columns = ["ts", "storage_service_name", "storage_hostname", "disk_id", "disk_capacity", "disk_free_space"]

"""
io_traces = None
with open("timestamped_io_operations_10.yml", "r", encoding="utf-8") as traces:
    io_traces = yaml.load(traces, Loader=yaml.SafeLoader)
    
ts_traces = pd.DataFrame(io_traces)
ts_traces
"""

ts_traces = pd.read_csv("timestamped_io_operations.csv", sep=",", header=0)
ts_traces

,ts,storage_service_name,storage_hostname,disk_id,disk_capacity,disk_free_space
0,1.600351e+09,simple_storage_44_5132,capacity3,/dev/ssd0/,1.030792e+12,1.030792e+12
1,1.600351e+09,simple_storage_45_5135,capacity3,/dev/ssd1/,1.030792e+12,1.030792e+12
2,1.600351e+09,simple_storage_46_5138,capacity3,/dev/ssd2/,1.030792e+12,1.030792e+12
3,1.600351e+09,simple_storage_47_5141,capacity3,/dev/ssd3/,1.030792e+12,1.030792e+12
4,1.600351e+09,simple_storage_48_5144,capacity4,/dev/hdd0/,4.294967e+12,4.294967e+12
...,...,...,...,...,...,...
19195,1.600820e+09,simple_storage_235_5705,capacity19,/dev/hdd7/,4.294967e+12,4.294967e+12
19196,1.600820e+09,simple_storage_236_5708,capacity19,/dev/ssd0/,1.030792e+12,1.030792e+12
19197,1.600820e+09,simple_storage_237_5711,capacity19,/dev/ssd1/,1.030792e+12,1.030792e+12
19198,1.600820e+09,simple_storage_238_5714,capacity19,/dev/ssd2/,1.030792e+12,1.030792e+12
19199,1.600820e+09,simple_storage_239_5717,capacity19,/dev/ssd3/,1.030792e+12,1.030792e+12

In [3]:
"""
dummy = {
    'ts': [1, 1, 10, 10, 1, 1, 10, 10], 
    'storage_service_name': ["storage1", "storage1", "storage1", "storage1", "storage2", "storage2", "storage2", "storage2"], 
    'disk': ["disk0", "disk1", "disk0", "disk1", "hdd1", "hdd2", "hdd1", "hdd2"],
    'capacity': [100, 150, 100, 150, 200, 120, 200, 120], 
    'free_space': [100, 150, 90, 110, 200, 120, 80, 20], 
    'allocations': [0, 0, 1, 1, 0, 0, 1, 1]
}
df_dummy = pd.DataFrame(dummy).sort_values(by="ts")
df_dummy["percent_free"] = df_dummy["free_space"].mul(100) 
df_dummy["percent_free"] = df_dummy["percent_free"] / df_dummy["capacity"] 
df_dummy
"""

ts_traces = ts_traces.sort_values(by="ts")
ts_traces["percent_free"] = ts_traces["disk_free_space"].mul(100) 
ts_traces["percent_free"] = ts_traces["percent_free"] / ts_traces["disk_capacity"] 
ts_traces["disk_capacity_tb"] = (ts_traces["disk_capacity"] / 1000 / 1000 / 1000 / 1000).round(decimals=2)

In [4]:
"""
unique_ts = pd.Series(df_dummy["ts"].unique()).sort_values()
unique_ts
"""

unique_ts = pd.Series(ts_traces["ts"].unique()).sort_values()
unique_ts

0     1.600351e+09
1     1.600351e+09
2     1.600354e+09
3     1.600356e+09
4     1.600358e+09
          ...
75    1.600753e+09
76    1.600820e+09
77    1.600820e+09
78    1.600820e+09
79    1.600820e+09
Length: 80, dtype: float64

In [5]:
"""
df_dummy_by_ts = df_dummy.groupby("ts")
keys = [key for key, _ in df_dummy_by_ts]
number_of_traces = len(keys)
"""

ts_traces_by_ts = ts_traces.groupby("ts")
keys = [key for key, _ in ts_traces_by_ts]
# print(keys)
number_of_traces = len(keys)

ts_traces_by_hostname = ts_traces.groupby("storage_hostname")
SERVER_NAMES = [key for key, _ in ts_traces_by_hostname]
# print(SERVER_NAMES)
NB_SERVERS = len(SERVER_NAMES)

In [6]:
import numpy as np
 
from bokeh.models import ColumnDataSource, RangeTool, DatetimeTickFormatter, NumeralTickFormatter
from bokeh.transform import factor_cmap, factor_mark

VERBOSE_DT_FORMATTER = DatetimeTickFormatter(days='%d/%m', hours="%d/%m - %Hh", hourmin='%H:%M', minutes = '%H:%M')
BYTE_FORMATTER = NumeralTickFormatter(format='0.0b')

X, Y, W, H = 0, 0, 1800, 1000


def treemap(df, col, x, y, dx, dy):
    """Normalize treemap"""
    sub_df = df.copy() # nlargest(N, col)
    normed = normalize_sizes(sub_df[col], dx, dy)
    blocks = squarify(normed, x, y, dx, dy)
    blocks_df = pd.DataFrame.from_dict(blocks).set_index(sub_df.index)
    return sub_df.join(blocks_df, how="left").reset_index()


def compute_dfs(df: pd.DataFrame, index: int):
    """Prepare generic source from dataframe"""
    
    ts_trace_1 = ts_traces[ts_traces["ts"] == unique_ts[index]]
    ts_trace_1 = ts_trace_1[["storage_hostname", "disk_id", "disk_capacity", "disk_free_space", "percent_free", "disk_capacity_tb"]]
    ts_trace_1_by_server = ts_trace_1[["storage_hostname", "disk_id", "disk_capacity"]].groupby("storage_hostname").sum("disk_capacity").sort_values(["storage_hostname"])
    
    blocks_by_server = treemap(ts_trace_1_by_server, "disk_capacity", X, Y, W, H)

    dfs = []
    for index, (storage_server, capacity, x, y, dx, dy) in blocks_by_server.iterrows():
        df = ts_trace_1[ts_trace_1.storage_hostname==storage_server]
        df = df.sort_values(["disk_capacity"])
        dfs.append(treemap(df, "disk_capacity", x, y, dx, dy))
    blocks = pd.concat(dfs)
    blocks["ytop"] = blocks.y + blocks.dy
    
    internal_blocks = blocks.copy()
    internal_blocks["x"] = internal_blocks["x"] + 4
    internal_blocks["y"] = internal_blocks["y"] + 4
    internal_blocks["dx"] = internal_blocks["dx"] - 8
    internal_blocks["dy"] = internal_blocks["dy"] - 8
    
    internal_blocks = internal_blocks.sort_values(["storage_hostname","disk_id"])
    internal_blocks = internal_blocks.reset_index(drop=True)
    internal_blocks = internal_blocks.drop("index", axis=1)
 
    
    return (blocks_by_server, internal_blocks)


def bkapp(doc):
    
    # Get a color map with 100 colors ranging from green to red
    colors = ["#3aeb34", "#ffba26", "#ff2a26"][::-1]
    cmap = matplotlib.colors.LinearSegmentedColormap.from_list("cmap_green_red", colors, N=100)
    hex_color_map = [matplotlib.colors.rgb2hex(cmap(i)) for i in range(cmap.N)]
    
    servers, disks = compute_dfs(ts_traces, 0)
    servers_source = ColumnDataSource(servers)
    disks_source = ColumnDataSource(disks)
    
    p = figure(
        width=W, 
        height=H, 
        toolbar_location=None,
        x_axis_location=None, 
        y_axis_location=None
    )
    p.x_range.range_padding = p.y_range.range_padding = 0
    p.grid.grid_line_color = None

    # Servers
    p.block('x', 'y', 'dx', 'dy', source=servers_source, 
            line_width=2, line_color="black",
            fill_alpha=0.8, fill_color=factor_cmap("storage_hostname", viridis(NB_SERVERS), SERVER_NAMES))
    
    # Disks
    disk_blk = p.block('x', 'y', 'dx', 'dy', source=disks_source, line_width=1, line_color="black",
            fill_alpha=0.8, fill_color=linear_cmap('percent_free', hex_color_map, 0, 100))
    # p.text('x', 'ytop', x_offset=2, y_offset=5, text="disk_id", source=disks_source,
           #text_font_size="8pt", text_baseline="top")
    # capa_text = p.text('x', 'ytop', x_offset=2, y_offset=20, text="disk_capacity_tb", source=disks_source,
           #text_font_size="10pt", text_baseline="top", text_align="left")
    
    # 
    # p.text('x', 'y', x_offset=2, text="storage_hostname", source=servers_source,
    #       text_font_size="14pt", text_color="white")
        
    hover = HoverTool(name='ytd_ave',tooltips=[
            ("Storage service", "@storage_hostname"),
            ("Disk", "@disk_id"),
            ("Free space (%)", "@percent_free"),
            ("Free space (Bytes)", "@disk_free_space"),
        ]
    )
    hover.renderers = [disk_blk]
    p.add_tools(hover)
        
    # Slider for trace id control
    trace_id = Slider(title="trace", value=0, start=0, end=(number_of_traces - 1), step=1)
    
    def update_data(attrname, old, new):
        # Get the current slider value
        index = trace_id.value
        
        ts_trace_1 = ts_traces[ts_traces["ts"] == unique_ts[index]]
        ts_trace_1 = ts_trace_1[["storage_hostname", "disk_id", "disk_capacity", "disk_free_space", "percent_free", "disk_capacity_tb"]].sort_values(["storage_hostname", "disk_id"])
        ts_trace_1 = ts_trace_1.reset_index()
        ts_trace_1 = ts_trace_1.drop("index", axis=1)
        
        # servers.update(ts_trace_1_by_server)
        disks.update(ts_trace_1)
        
        # servers_source = servers
        disks_source.data = disks
        
        """
        new_servers, new_disks = compute_dfs(ts_traces, index)
        servers_source = new_servers
        disks_source.data = new_disks
        """
        
    trace_id.on_change('value', update_data)

    doc.add_root(column(p, trace_id))

    doc.theme = Theme(json=yaml.load("""
        attrs:
            figure:
                background_fill_color: "#DDDDDD"
                outline_line_color: white
                toolbar_location: above
                height: 700
                width: 1200
            Grid:
                grid_line_dash: [6, 4]
                grid_line_color: white
    """, Loader=yaml.FullLoader))

In [7]:
show(bkapp) # notebook_url="http://localhost:8888"

In [8]:
servers, disks = compute_dfs(ts_traces, 0)
disks

,storage_hostname,disk_id,disk_capacity,disk_free_space,percent_free,disk_capacity_tb,x,y,dx,dy,ytop
0,capacity0,/dev/hdd0/,4.294967e+12,4.294967e+12,100.0,4.29,4.000,39.714286,82.000,103.607143,147.321429
1,capacity0,/dev/hdd1/,4.294967e+12,4.294967e+12,100.0,4.29,94.000,39.714286,82.000,103.607143,147.321429
2,capacity0,/dev/hdd2/,4.294967e+12,4.294967e+12,100.0,4.29,184.000,39.714286,82.000,103.607143,147.321429
3,capacity0,/dev/hdd3/,4.294967e+12,4.294967e+12,100.0,4.29,4.000,151.321429,100.000,85.005952,240.327381
4,capacity0,/dev/hdd4/,4.294967e+12,4.294967e+12,100.0,4.29,4.000,244.327381,100.000,85.005952,333.333333
...,...,...,...,...,...,...,...,...,...,...,...
235,capacity9,/dev/hdd7/,4.294967e+12,4.294967e+12,100.0,4.29,1655.500,936.359307,140.500,59.640693,1000.000000
236,capacity9,/dev/ssd0/,1.030792e+12,1.030792e+12,100.0,1.03,1742.125,640.363636,53.875,30.961039,675.324675
237,capacity9,/dev/ssd1/,1.030792e+12,1.030792e+12,100.0,1.03,1680.250,640.363636,53.875,30.961039,675.324675
238,capacity9,/dev/ssd2/,1.030792e+12,1.030792e+12,100.0,1.03,1556.500,640.363636,53.875,30.961039,675.324675
239,capacity9,/dev/ssd3/,1.030792e+12,1.030792e+12,100.0,1.03,1618.375,640.363636,53.875,30.961039,675.324675

In [9]:
ts_trace_1 = ts_traces[ts_traces["ts"] == unique_ts[5]]
ts_trace_1 = ts_trace_1[["storage_hostname", "disk_id", "disk_capacity", "disk_free_space", "percent_free", "disk_capacity_tb"]].sort_values(["storage_hostname", "disk_id"])
ts_trace_1 = ts_trace_1.reset_index()
ts_trace_1 = ts_trace_1.drop("index", axis=1)
ts_trace_1

,storage_hostname,disk_id,disk_capacity,disk_free_space,percent_free,disk_capacity_tb
0,capacity0,/dev/hdd0/,4.294967e+12,4.294967e+12,100.0,4.29
1,capacity0,/dev/hdd1/,4.294967e+12,4.294967e+12,100.0,4.29
2,capacity0,/dev/hdd2/,4.294967e+12,4.294967e+12,100.0,4.29
3,capacity0,/dev/hdd3/,4.294967e+12,4.294967e+12,100.0,4.29
4,capacity0,/dev/hdd4/,4.294967e+12,4.294967e+12,100.0,4.29
...,...,...,...,...,...,...
235,capacity9,/dev/hdd7/,4.294967e+12,4.294967e+12,100.0,4.29
236,capacity9,/dev/ssd0/,1.030792e+12,1.030792e+12,100.0,1.03
237,capacity9,/dev/ssd1/,1.030792e+12,1.030792e+12,100.0,1.03
238,capacity9,/dev/ssd2/,1.030792e+12,1.030792e+12,100.0,1.03
239,capacity9,/dev/ssd3/,1.030792e+12,1.030792e+12,100.0,1.03

In [10]:
disks.update(ts_trace_1)
disks

,storage_hostname,disk_id,disk_capacity,disk_free_space,percent_free,disk_capacity_tb,x,y,dx,dy,ytop
0,capacity0,/dev/hdd0/,4.294967e+12,4.294967e+12,100.0,4.29,4.000,39.714286,82.000,103.607143,147.321429
1,capacity0,/dev/hdd1/,4.294967e+12,4.294967e+12,100.0,4.29,94.000,39.714286,82.000,103.607143,147.321429
2,capacity0,/dev/hdd2/,4.294967e+12,4.294967e+12,100.0,4.29,184.000,39.714286,82.000,103.607143,147.321429
3,capacity0,/dev/hdd3/,4.294967e+12,4.294967e+12,100.0,4.29,4.000,151.321429,100.000,85.005952,240.327381
4,capacity0,/dev/hdd4/,4.294967e+12,4.294967e+12,100.0,4.29,4.000,244.327381,100.000,85.005952,333.333333
...,...,...,...,...,...,...,...,...,...,...,...
235,capacity9,/dev/hdd7/,4.294967e+12,4.294967e+12,100.0,4.29,1655.500,936.359307,140.500,59.640693,1000.000000
236,capacity9,/dev/ssd0/,1.030792e+12,1.030792e+12,100.0,1.03,1742.125,640.363636,53.875,30.961039,675.324675
237,capacity9,/dev/ssd1/,1.030792e+12,1.030792e+12,100.0,1.03,1680.250,640.363636,53.875,30.961039,675.324675
238,capacity9,/dev/ssd2/,1.030792e+12,1.030792e+12,100.0,1.03,1556.500,640.363636,53.875,30.961039,675.324675
239,capacity9,/dev/ssd3/,1.030792e+12,1.030792e+12,100.0,1.03,1618.375,640.363636,53.875,30.961039,675.324675