In [1]:
import yaml
import datetime as dt

import pandas as pd
import numpy as np
import matplotlib

from bokeh.layouts import column
from bokeh.models import (ColumnDataSource, Slider, LabelSet, CategoricalColorMapper, DataTable, HoverTool, IntEditor,
                          NumberEditor, NumberFormatter, SelectEditor,
                          StringEditor, StringFormatter, TableColumn, LinearColorMapper, ContinuousColorMapper)
from bokeh.plotting import figure
from bokeh.themes import Theme
from bokeh.palettes import Spectral4, viridis, Viridis256
from bokeh.io import show, output_notebook
from bokeh.transform import jitter, factor_cmap, linear_cmap

from squarify import normalize_sizes, squarify
import colorcet as cc


output_notebook()

In [2]:
## IMPORT IO TRACES AND CREATE TWO DATAFRAMES

columns = ["ts", "storage_service_name", "storage_hostname", "disk_id", "disk_capacity", "disk_free_space", "file_name"]
dtypes = {
    "ts": "Float64", 
    "storage_service_name": "string", 
    "storage_hostname": "string", 
    "disk_id": "string", 
    "disk_capacity": "UInt64",
    "disk_free_space": "UInt64",
    "file_name": "string"
}

"""
io_traces = None
with open("timestamped_io_operations_10.yml", "r", encoding="utf-8") as traces:
    io_traces = yaml.load(traces, Loader=yaml.SafeLoader)
    
ts_traces = pd.DataFrame(io_traces)
ts_traces
"""

ts_traces = pd.read_csv("timestamped_io_operations.csv", sep=",", header=0, dtype=dtypes)
ts_traces

,ts,action_name,storage_service_name,storage_hostname,disk_id,disk_capacity,disk_free_space,file_name
0,0.0,11,simple_storage_0_5000,lustre_OSS0,/dev/hdd0/,200000000000,200000000000,NoFile
1,0.0,11,simple_storage_1_5003,lustre_OSS0,/dev/hdd1/,200000000000,200000000000,NoFile
2,0.0,11,simple_storage_2_5006,lustre_OSS1,/dev/hdd0/,200000000000,200000000000,NoFile
3,0.0,11,simple_storage_3_5009,lustre_OSS1,/dev/hdd1/,200000000000,200000000000,NoFile
4,0.0,11,simple_storage_4_5012,lustre_OSS2,/dev/hdd0/,200000000000,200000000000,NoFile
...,...,...,...,...,...,...,...,...
283,107527.648229,9,simple_storage_10_5030,lustre_OSS5,/dev/hdd0/,200000000000,199360000000,ouptut_data_file_6_part_3
284,107527.652809,10,simple_storage_4_5012,lustre_OSS2,/dev/hdd0/,200000000000,200000000000,ouptut_data_file_6_part_0
285,107527.652809,10,simple_storage_6_5018,lustre_OSS3,/dev/hdd0/,200000000000,200000000000,ouptut_data_file_6_part_1
286,107527.652809,10,simple_storage_8_5024,lustre_OSS4,/dev/hdd0/,200000000000,200000000000,ouptut_data_file_6_part_2
287,107527.652809,10,simple_storage_10_5030,lustre_OSS5,/dev/hdd0/,200000000000,200000000000,ouptut_data_file_6_part_3

In [3]:
ts_traces = ts_traces.sort_values(by=["ts", "storage_service_name"])
ts_traces["percent_free"] = ts_traces["disk_free_space"].mul(100) 
ts_traces["percent_free"] = ts_traces["percent_free"] / ts_traces["disk_capacity"] 
ts_traces["disk_capacity_tb"] = (ts_traces["disk_capacity"] / 1000 / 1000 / 1000 / 1000).round(decimals=2)

ts_trace_0 = ts_traces[ts_traces["action_name"] == 11]
ts_trace_simulation = ts_traces[ts_traces["action_name"] != 11]

In [4]:
ts_trace_0

,ts,action_name,storage_service_name,storage_hostname,disk_id,disk_capacity,disk_free_space,file_name,percent_free,disk_capacity_tb
0,0.0,11,simple_storage_0_5000,lustre_OSS0,/dev/hdd0/,200000000000,200000000000,NoFile,100.0,0.2
10,0.0,11,simple_storage_10_5030,lustre_OSS5,/dev/hdd0/,200000000000,200000000000,NoFile,100.0,0.2
11,0.0,11,simple_storage_11_5033,lustre_OSS5,/dev/hdd1/,200000000000,200000000000,NoFile,100.0,0.2
12,0.0,11,simple_storage_12_5036,lustre_OSS6,/dev/hdd0/,200000000000,200000000000,NoFile,100.0,0.2
13,0.0,11,simple_storage_13_5039,lustre_OSS6,/dev/hdd1/,200000000000,200000000000,NoFile,100.0,0.2
14,0.0,11,simple_storage_14_5042,lustre_OSS7,/dev/hdd0/,200000000000,200000000000,NoFile,100.0,0.2
15,0.0,11,simple_storage_15_5045,lustre_OSS7,/dev/hdd1/,200000000000,200000000000,NoFile,100.0,0.2
1,0.0,11,simple_storage_1_5003,lustre_OSS0,/dev/hdd1/,200000000000,200000000000,NoFile,100.0,0.2
2,0.0,11,simple_storage_2_5006,lustre_OSS1,/dev/hdd0/,200000000000,200000000000,NoFile,100.0,0.2
3,0.0,11,simple_storage_3_5009,lustre_OSS1,/dev/hdd1/,200000000000,200000000000,NoFile,100.0,0.2
4,0.0,11,simple_storage_4_5012,lustre_OSS2,/dev/hdd0/,200000000000,200000000000,NoFile,100.0,0.2
5,0.0,11,simple_storage_5_5015,lustre_OSS2,/dev/hdd1/,200000000000,200000000000,NoFile,100.0,0.2
6,0.0,11,simple_storage_6_5018,lustre_OSS3,/dev/hdd0/,200000000000,200000000000,NoFile,100.0,0.2
7,0.0,11,simple_storage_7_5021,lustre_OSS3,/dev/hdd1/,200000000000,200000000000,NoFile,100.0,0.2
8,0.0,11,simple_storage_8_5024,lustre_OSS4,/dev/hdd0/,200000000000,200000000000,NoFile,100.0,0.2
9,0.0,11,simple_storage_9_5027,lustre_OSS4,/dev/hdd1/,200000000000,200000000000,NoFile,100.0,0.2

In [5]:
ts_trace_simulation

,ts,action_name,storage_service_name,storage_hostname,disk_id,disk_capacity,disk_free_space,file_name,percent_free,disk_capacity_tb
17,0.001771,5,simple_storage_10_5030,lustre_OSS5,/dev/hdd0/,200000000000,199360000000,input_data_file_1_part_1,99.68,0.2
18,0.001771,5,simple_storage_12_5036,lustre_OSS6,/dev/hdd0/,200000000000,199360000000,input_data_file_1_part_2,99.68,0.2
19,0.001771,5,simple_storage_14_5042,lustre_OSS7,/dev/hdd0/,200000000000,199360000000,input_data_file_1_part_3,99.68,0.2
20,0.001771,5,simple_storage_1_5003,lustre_OSS0,/dev/hdd1/,200000000000,199360000000,input_data_file_1_part_4,99.68,0.2
21,0.001771,5,simple_storage_3_5009,lustre_OSS1,/dev/hdd1/,200000000000,199360000000,input_data_file_1_part_5,99.68,0.2
...,...,...,...,...,...,...,...,...,...,...
282,107527.648229,9,simple_storage_8_5024,lustre_OSS4,/dev/hdd0/,200000000000,199360000000,ouptut_data_file_6_part_2,99.68,0.2
287,107527.652809,10,simple_storage_10_5030,lustre_OSS5,/dev/hdd0/,200000000000,200000000000,ouptut_data_file_6_part_3,100.0,0.2
284,107527.652809,10,simple_storage_4_5012,lustre_OSS2,/dev/hdd0/,200000000000,200000000000,ouptut_data_file_6_part_0,100.0,0.2
285,107527.652809,10,simple_storage_6_5018,lustre_OSS3,/dev/hdd0/,200000000000,200000000000,ouptut_data_file_6_part_1,100.0,0.2
286,107527.652809,10,simple_storage_8_5024,lustre_OSS4,/dev/hdd0/,200000000000,200000000000,ouptut_data_file_6_part_2,100.0,0.2

In [6]:
"""
unique_ts = pd.Series(df_dummy["ts"].unique()).sort_values()
unique_ts
"""

unique_ts = pd.Series(ts_traces["ts"].unique()).sort_values()
unique_ts

0               0.0
1          0.001771
2          6.412702
3       2512.822424
4       2519.225849
5       2526.637924
6       2526.647084
7       2527.651092
8       2527.655671
9       7500.001771
10      7506.411557
11     10012.820707
12     10019.224132
13     10026.636207
14     10026.644221
15     10027.648229
16     10027.652809
17     21600.001771
18     21606.411557
19     24112.820707
20     24119.224132
21     24126.636207
22     24126.644221
23     24127.648229
24     24127.652809
25     83400.001771
26     83406.412702
27     85912.822424
28     85919.225849
29     85926.637924
30     85926.647084
31     85927.651092
32     85927.655671
33     90900.001771
34     90906.411557
35     93412.820707
36     93419.224132
37     93426.636207
38     93426.644221
39     93427.648229
40     93427.652809
41    105000.001771
42    105006.411557
43    107512.820707
44    107519.224132
45    107526.636207
46    107526.644221
47    107527.648229
48    107527.652809
dtype: Float64

In [7]:
"""
df_dummy_by_ts = df_dummy.groupby("ts")
keys = [key for key, _ in df_dummy_by_ts]
number_of_traces = len(keys)
"""

ts_traces_by_ts = ts_traces.groupby("ts")
keys = [key for key, _ in ts_traces_by_ts]
# print(keys)
number_of_traces = len(keys)

ts_traces_by_hostname = ts_traces.groupby("storage_hostname")
SERVER_NAMES = [key for key, _ in ts_traces_by_hostname]
# print(SERVER_NAMES)
NB_SERVERS = len(SERVER_NAMES)

In [8]:
import numpy as np
 
from bokeh.models import ColumnDataSource, RangeTool, DatetimeTickFormatter, NumeralTickFormatter
from bokeh.transform import factor_cmap, factor_mark

VERBOSE_DT_FORMATTER = DatetimeTickFormatter(days='%d/%m', hours="%d/%m - %Hh", hourmin='%H:%M', minutes = '%H:%M')
BYTE_FORMATTER = NumeralTickFormatter(format='0.0b')

X, Y, W, H = 0, 0, 1800, 1000
disks = None


def treemap(df, col, x, y, dx, dy):
    """Normalize treemap"""
    sub_df = df.copy() # nlargest(N, col)
    normed = normalize_sizes(sub_df[col], dx, dy)
    blocks = squarify(normed, x, y, dx, dy)
    blocks_df = pd.DataFrame.from_dict(blocks).set_index(sub_df.index)
    return sub_df.join(blocks_df, how="left").reset_index()


def compute_dfs(df: pd.DataFrame, index: int):
    """Prepare generic source from dataframe"""
    
    ts_trace_1 = ts_traces[ts_traces["ts"] == unique_ts[index]]
    ts_trace_1 = ts_trace_1[
        [
            "storage_hostname", 
            "disk_id", 
            "disk_capacity", 
            "disk_free_space", 
            "percent_free", 
            "disk_capacity_tb", 
            "file_name"
        ]
    ]
    ts_trace_1_by_server = (ts_trace_1[["storage_hostname", "disk_id", "disk_capacity", "file_name"]]
                            .groupby("storage_hostname").sum("disk_capacity").sort_values(["storage_hostname"]))
    
    blocks_by_server = treemap(ts_trace_1_by_server, "disk_capacity", X, Y, W, H)

    dfs = []
    for index, (storage_server, capacity, x, y, dx, dy) in blocks_by_server.iterrows():
        df = ts_trace_1[ts_trace_1.storage_hostname==storage_server]
        df = df.sort_values(["disk_capacity"])
        dfs.append(treemap(df, "disk_capacity", x, y, dx, dy))
    blocks = pd.concat(dfs)
    blocks["ytop"] = blocks.y + blocks.dy
    
    internal_blocks = blocks.copy()
    internal_blocks["x"] = internal_blocks["x"] + 5
    internal_blocks["y"] = internal_blocks["y"] + 5
    internal_blocks["dx"] = internal_blocks["dx"] - 10
    internal_blocks["dy"] = internal_blocks["dy"] - 10
    
    internal_blocks = internal_blocks.sort_values(["storage_hostname", "disk_id", "file_name"])
    internal_blocks = internal_blocks.reset_index(drop=True)
    internal_blocks = internal_blocks.drop("index", axis=1)
    
    return (blocks_by_server, internal_blocks)


def bkapp(doc):
        
    # Get a color map with 100 colors ranging from green to red
    colors = ["#3aeb34", "#ffba26", "#ff2a26"][::-1]
    cmap = matplotlib.colors.LinearSegmentedColormap.from_list("cmap_green_red", colors, N=100)
    hex_color_map = [matplotlib.colors.rgb2hex(cmap(i)) for i in range(cmap.N)]
    
    global disks
    servers, disks = compute_dfs(ts_traces, 0)
    servers_source = ColumnDataSource(servers)
    disks_source = ColumnDataSource(disks)
    
    p = figure(
        width=W, 
        height=H, 
        toolbar_location=None,
        x_axis_location=None, 
        y_axis_location=None
    )
    p.x_range.range_padding = p.y_range.range_padding = 0
    p.grid.grid_line_color = None

    # Servers
    p.block('x', 'y', 'dx', 'dy', source=servers_source, 
            line_width=2, line_color="black",
            fill_alpha=0.8, fill_color=factor_cmap("storage_hostname", viridis(NB_SERVERS), SERVER_NAMES))
    
    # Disks
    disk_blk = p.block('x', 'y', 'dx', 'dy', source=disks_source, line_width=1, line_color="black",
            fill_alpha=0.8, fill_color=linear_cmap('percent_free', hex_color_map, 0, 100))
    # p.text('x', 'ytop', x_offset=2, y_offset=5, text="disk_id", source=disks_source,
           #text_font_size="8pt", text_baseline="top")
    # capa_text = p.text('x', 'ytop', x_offset=2, y_offset=20, text="disk_capacity_tb", source=disks_source,
           #text_font_size="10pt", text_baseline="top", text_align="left")
    
    # 
    # p.text('x', 'y', x_offset=2, text="storage_hostname", source=servers_source,
    #       text_font_size="14pt", text_color="white")
        
    hover = HoverTool(name='ytd_ave',tooltips=[
            ("Storage service", "@storage_hostname"),
            ("Disk", "@disk_id"),
            ("Free space (%)", "@percent_free"),
            ("Free space (Bytes)", "@disk_free_space"),
            ("File", "@file_name")
        ]
    )
    hover.renderers = [disk_blk]
    p.add_tools(hover)
        
    # Slider for trace id control
    trace_id = Slider(title="trace", value=0, start=0, end=(number_of_traces - 1), step=1)
    
    def update_data(attrname, old, new):
        # Get the current slider value
        index = trace_id.value
        
        ts_trace_1 = ts_traces[ts_traces["ts"] == unique_ts[index]]
        ts_trace_1 = ts_trace_1[["storage_hostname", "disk_id", "disk_capacity", "disk_free_space", "percent_free", "disk_capacity_tb", "file_name"]].sort_values(["storage_hostname", "disk_id", "file_name"])
        ts_trace_1 = ts_trace_1.reset_index()
        ts_trace_1 = ts_trace_1.drop("index", axis=1)
        ts_trace_1 = ts_trace_1.set_index(keys=["storage_hostname", "disk_id"])
        ts_trace_1 = ts_trace_1.groupby(["storage_hostname", "disk_id"]).agg(
            {
                "disk_capacity": "first", 
                "disk_free_space": "first",
                "percent_free": "first",
                "disk_capacity_tb": "first",
                "file_name": ', '.join
            }
        )
        print(ts_trace_1)
        
        # servers.update(ts_trace_1_by_server)
        global disks
        disks = disks.set_index(keys=["storage_hostname", "disk_id"])
        temp_file_name = disks["file_name"].copy(deep=True)
        disks.update(ts_trace_1)
        print("### Disks after update")
        
        print("##########################")
        disks["previous_file_name"] = temp_file_name
        print(disks)
        disks["file_name"] = disks["previous_file_name"] + ", " + disks["file_name"]
        # disks["previous_file_name", "file_name"].apply(lambda x: ", ".join(x), axis=1)
        # disks.drop("previous_filename", axis=1)
        print("####### Disks after apply")
        print(disks)
        print("###########################2")
        disks = disks.reset_index()
        
        #n_disks = pd.concat([disks,ts_trace_1]).drop_duplicates(['storage_hostname','disk_id'],keep='last')
        #n_disks = n_disks.reset_index()
        #n_disks = n_disks.drop("index", axis=1)
        # disks.update(ts_trace_1)
        
        # servers_source = servers
        disks_source.data = disks
        
        """
        new_servers, new_disks = compute_dfs(ts_traces, index)
        servers_source = new_servers
        disks_source.data = new_disks
        """
        
    trace_id.on_change('value', update_data)

    doc.add_root(column(p, trace_id))

    doc.theme = Theme(json=yaml.load("""
        attrs:
            figure:
                background_fill_color: "#DDDDDD"
                outline_line_color: white
                toolbar_location: above
                height: 700
                width: 1200
            Grid:
                grid_line_dash: [6, 4]
                grid_line_color: white
    """, Loader=yaml.FullLoader))

In [9]:
show(bkapp) # notebook_url="http://localhost:8888"

In [10]:
servers, disks = compute_dfs(ts_traces, 0)
disks

,storage_hostname,disk_id,disk_capacity,disk_free_space,percent_free,disk_capacity_tb,file_name,x,y,dx,dy,ytop
0,lustre_OSS0,/dev/hdd0/,200000000000,200000000000,100.0,0.2,NoFile,5.0,5.0,440.0,240.0,250.0
1,lustre_OSS0,/dev/hdd1/,200000000000,200000000000,100.0,0.2,NoFile,5.0,255.0,440.0,240.0,500.0
2,lustre_OSS1,/dev/hdd0/,200000000000,200000000000,100.0,0.2,NoFile,5.0,505.0,440.0,240.0,750.0
3,lustre_OSS1,/dev/hdd1/,200000000000,200000000000,100.0,0.2,NoFile,5.0,755.0,440.0,240.0,1000.0
4,lustre_OSS2,/dev/hdd0/,200000000000,200000000000,100.0,0.2,NoFile,455.0,5.0,440.0,240.0,250.0
5,lustre_OSS2,/dev/hdd1/,200000000000,200000000000,100.0,0.2,NoFile,455.0,255.0,440.0,240.0,500.0
6,lustre_OSS3,/dev/hdd0/,200000000000,200000000000,100.0,0.2,NoFile,455.0,505.0,440.0,240.0,750.0
7,lustre_OSS3,/dev/hdd1/,200000000000,200000000000,100.0,0.2,NoFile,455.0,755.0,440.0,240.0,1000.0
8,lustre_OSS4,/dev/hdd0/,200000000000,200000000000,100.0,0.2,NoFile,905.0,5.0,440.0,240.0,250.0
9,lustre_OSS4,/dev/hdd1/,200000000000,200000000000,100.0,0.2,NoFile,905.0,255.0,440.0,240.0,500.0
10,lustre_OSS5,/dev/hdd0/,200000000000,200000000000,100.0,0.2,NoFile,1355.0,5.0,440.0,240.0,250.0
11,lustre_OSS5,/dev/hdd1/,200000000000,200000000000,100.0,0.2,NoFile,1355.0,255.0,440.0,240.0,500.0
12,lustre_OSS6,/dev/hdd0/,200000000000,200000000000,100.0,0.2,NoFile,905.0,505.0,440.0,240.0,750.0
13,lustre_OSS6,/dev/hdd1/,200000000000,200000000000,100.0,0.2,NoFile,905.0,755.0,440.0,240.0,1000.0
14,lustre_OSS7,/dev/hdd0/,200000000000,200000000000,100.0,0.2,NoFile,1355.0,505.0,440.0,240.0,750.0
15,lustre_OSS7,/dev/hdd1/,200000000000,200000000000,100.0,0.2,NoFile,1355.0,755.0,440.0,240.0,1000.0

                             disk_capacity  disk_free_space  percent_free
storage_hostname disk_id
lustre_OSS0      /dev/hdd1/   200000000000     199360000000         99.68  \
lustre_OSS1      /dev/hdd1/   200000000000     199360000000         99.68
lustre_OSS2      /dev/hdd1/   200000000000     199360000000         99.68
lustre_OSS3      /dev/hdd1/   200000000000     199360000000         99.68
lustre_OSS4      /dev/hdd0/   200000000000     199360000000         99.68
lustre_OSS5      /dev/hdd0/   200000000000     199360000000         99.68
lustre_OSS6      /dev/hdd0/   200000000000     199360000000         99.68
lustre_OSS7      /dev/hdd0/   200000000000     199360000000         99.68

                             disk_capacity_tb                 file_name
storage_hostname disk_id
lustre_OSS0      /dev/hdd1/               0.2  input_data_file_1_part_4
lustre_OSS1      /dev/hdd1/               0.2  input_data_file_1_part_5
lustre_OSS2      /dev/hdd1/               0.2  input_data_file_1_part_6
lustre_OSS3      /dev/hdd1/               0.2  input_data_file_1_part_7
lustre_OSS4      /dev/hdd0/               0.2  input_data_file_1_part_0
lustre_OSS5      /dev/hdd0/               0.2  input_data_file_1_part_1
lustre_OSS6      /dev/hdd0/               0.2  input_data_file_1_part_2
lustre_OSS7      /dev/hdd0/               0.2  input_data_file_1_part_3
### Disks after update
##########################
                             disk_capacity  disk_free_space  percent_free
storage_hostname disk_id
lustre_OSS0      /dev/hdd0/   200000000000     200000000000         100.0  \
                 /dev/hdd1/   200000000000     199360000000         99.68
lustre_OSS1      /dev/hdd0/   200000000000     200000000000         100.0
                 /dev/hdd1/   200000000000     199360000000         99.68
lustre_OSS2      /dev/hdd0/   200000000000     200000000000         100.0
                 /dev/hdd1/   200000000000     199360000000         99.68
lustre_OSS3      /dev/hdd0/   200000000000     200000000000         100.0
                 /dev/hdd1/   200000000000     199360000000         99.68
lustre_OSS4      /dev/hdd0/   200000000000     199360000000         99.68
                 /dev/hdd1/   200000000000     200000000000         100.0
lustre_OSS5      /dev/hdd0/   200000000000     199360000000         99.68
                 /dev/hdd1/   200000000000     200000000000         100.0
lustre_OSS6      /dev/hdd0/   200000000000     199360000000         99.68
                 /dev/hdd1/   200000000000     200000000000         100.0
lustre_OSS7      /dev/hdd0/   200000000000     199360000000         99.68
                 /dev/hdd1/   200000000000     200000000000         100.0

                             disk_capacity_tb                 file_name
storage_hostname disk_id
lustre_OSS0      /dev/hdd0/               0.2                    NoFile  \
                 /dev/hdd1/               0.2  input_data_file_1_part_4
lustre_OSS1      /dev/hdd0/               0.2                    NoFile
                 /dev/hdd1/               0.2  input_data_file_1_part_5
lustre_OSS2      /dev/hdd0/               0.2                    NoFile
                 /dev/hdd1/               0.2  input_data_file_1_part_6
lustre_OSS3      /dev/hdd0/               0.2                    NoFile
                 /dev/hdd1/               0.2  input_data_file_1_part_7
lustre_OSS4      /dev/hdd0/               0.2  input_data_file_1_part_0
                 /dev/hdd1/               0.2                    NoFile
lustre_OSS5      /dev/hdd0/               0.2  input_data_file_1_part_1
                 /dev/hdd1/               0.2                    NoFile
lustre_OSS6      /dev/hdd0/               0.2  input_data_file_1_part_2
                 /dev/hdd1/               0.2                    NoFile
lustre_OSS7      /dev/hdd0/               0.2  input_data_file_1_part_3
                 /dev/hdd1/               0.2                    NoFile

                                  x      y     dx     dy    ytop
storage_hostname disk_id
lustre_OSS0      /dev/hdd0/     5.0    5.0  440.0  240.0   250.0  \
                 /dev/hdd1/     5.0  255.0  440.0  240.0   500.0
lustre_OSS1      /dev/hdd0/     5.0  505.0  440.0  240.0   750.0
                 /dev/hdd1/     5.0  755.0  440.0  240.0  1000.0
lustre_OSS2      /dev/hdd0/   455.0    5.0  440.0  240.0   250.0
                 /dev/hdd1/   455.0  255.0  440.0  240.0   500.0
lustre_OSS3      /dev/hdd0/   455.0  505.0  440.0  240.0   750.0
                 /dev/hdd1/   455.0  755.0  440.0  240.0  1000.0
lustre_OSS4      /dev/hdd0/   905.0    5.0  440.0  240.0   250.0
                 /dev/hdd1/   905.0  255.0  440.0  240.0   500.0
lustre_OSS5      /dev/hdd0/  1355.0    5.0  440.0  240.0   250.0
                 /dev/hdd1/  1355.0  255.0  440.0  240.0   500.0
lustre_OSS6      /dev/hdd0/   905.0  505.0  440.0  240.0   750.0
                 /dev/hdd1/   905.0  755.0  440.0  240.0  1000.0
lustre_OSS7      /dev/hdd0/  1355.0  505.0  440.0  240.0   750.0
                 /dev/hdd1/  1355.0  755.0  440.0  240.0  1000.0

                            previous_file_name
storage_hostname disk_id
lustre_OSS0      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS1      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS2      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS3      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS4      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS5      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS6      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS7      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
####### Disks after apply
                             disk_capacity  disk_free_space  percent_free
storage_hostname disk_id
lustre_OSS0      /dev/hdd0/   200000000000     200000000000         100.0  \
                 /dev/hdd1/   200000000000     199360000000         99.68
lustre_OSS1      /dev/hdd0/   200000000000     200000000000         100.0
                 /dev/hdd1/   200000000000     199360000000         99.68
lustre_OSS2      /dev/hdd0/   200000000000     200000000000         100.0
                 /dev/hdd1/   200000000000     199360000000         99.68
lustre_OSS3      /dev/hdd0/   200000000000     200000000000         100.0
                 /dev/hdd1/   200000000000     199360000000         99.68
lustre_OSS4      /dev/hdd0/   200000000000     199360000000         99.68
                 /dev/hdd1/   200000000000     200000000000         100.0
lustre_OSS5      /dev/hdd0/   200000000000     199360000000         99.68
                 /dev/hdd1/   200000000000     200000000000         100.0
lustre_OSS6      /dev/hdd0/   200000000000     199360000000         99.68
                 /dev/hdd1/   200000000000     200000000000         100.0
lustre_OSS7      /dev/hdd0/   200000000000     199360000000         99.68
                 /dev/hdd1/   200000000000     200000000000         100.0

                             disk_capacity_tb                 file_name
storage_hostname disk_id
lustre_OSS0      /dev/hdd0/               0.2                    NoFile  \
                 /dev/hdd1/               0.2  input_data_file_1_part_4
lustre_OSS1      /dev/hdd0/               0.2                    NoFile
                 /dev/hdd1/               0.2  input_data_file_1_part_5
lustre_OSS2      /dev/hdd0/               0.2                    NoFile
                 /dev/hdd1/               0.2  input_data_file_1_part_6
lustre_OSS3      /dev/hdd0/               0.2                    NoFile
                 /dev/hdd1/               0.2  input_data_file_1_part_7
lustre_OSS4      /dev/hdd0/               0.2  input_data_file_1_part_0
                 /dev/hdd1/               0.2                    NoFile
lustre_OSS5      /dev/hdd0/               0.2  input_data_file_1_part_1
                 /dev/hdd1/               0.2                    NoFile
lustre_OSS6      /dev/hdd0/               0.2  input_data_file_1_part_2
                 /dev/hdd1/               0.2                    NoFile
lustre_OSS7      /dev/hdd0/               0.2  input_data_file_1_part_3
                 /dev/hdd1/               0.2                    NoFile

                                  x      y     dx     dy    ytop
storage_hostname disk_id
lustre_OSS0      /dev/hdd0/     5.0    5.0  440.0  240.0   250.0  \
                 /dev/hdd1/     5.0  255.0  440.0  240.0   500.0
lustre_OSS1      /dev/hdd0/     5.0  505.0  440.0  240.0   750.0
                 /dev/hdd1/     5.0  755.0  440.0  240.0  1000.0
lustre_OSS2      /dev/hdd0/   455.0    5.0  440.0  240.0   250.0
                 /dev/hdd1/   455.0  255.0  440.0  240.0   500.0
lustre_OSS3      /dev/hdd0/   455.0  505.0  440.0  240.0   750.0
                 /dev/hdd1/   455.0  755.0  440.0  240.0  1000.0
lustre_OSS4      /dev/hdd0/   905.0    5.0  440.0  240.0   250.0
                 /dev/hdd1/   905.0  255.0  440.0  240.0   500.0
lustre_OSS5      /dev/hdd0/  1355.0    5.0  440.0  240.0   250.0
                 /dev/hdd1/  1355.0  255.0  440.0  240.0   500.0
lustre_OSS6      /dev/hdd0/   905.0  505.0  440.0  240.0   750.0
                 /dev/hdd1/   905.0  755.0  440.0  240.0  1000.0
lustre_OSS7      /dev/hdd0/  1355.0  505.0  440.0  240.0   750.0
                 /dev/hdd1/  1355.0  755.0  440.0  240.0  1000.0

                            previous_file_name
storage_hostname disk_id
lustre_OSS0      /dev/hdd0/             NoFile  \
                 /dev/hdd1/             NoFile
lustre_OSS1      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS2      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS3      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS4      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS5      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS6      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile
lustre_OSS7      /dev/hdd0/             NoFile
                 /dev/hdd1/             NoFile

                                                   file_name2
storage_hostname disk_id
lustre_OSS0      /dev/hdd0/                    NoFile, NoFile
                 /dev/hdd1/  NoFile, input_data_file_1_part_4
lustre_OSS1      /dev/hdd0/                    NoFile, NoFile
                 /dev/hdd1/  NoFile, input_data_file_1_part_5
lustre_OSS2      /dev/hdd0/                    NoFile, NoFile
                 /dev/hdd1/  NoFile, input_data_file_1_part_6
lustre_OSS3      /dev/hdd0/                    NoFile, NoFile
                 /dev/hdd1/  NoFile, input_data_file_1_part_7
lustre_OSS4      /dev/hdd0/  NoFile, input_data_file_1_part_0
                 /dev/hdd1/                    NoFile, NoFile
lustre_OSS5      /dev/hdd0/  NoFile, input_data_file_1_part_1
                 /dev/hdd1/                    NoFile, NoFile
lustre_OSS6      /dev/hdd0/  NoFile, input_data_file_1_part_2
                 /dev/hdd1/                    NoFile, NoFile
lustre_OSS7      /dev/hdd0/  NoFile, input_data_file_1_part_3
                 /dev/hdd1/                    NoFile, NoFile
###########################2

In [ ]:
ts_trace_1 = ts_traces[ts_traces["ts"] == unique_ts[1]]
ts_trace_1 = ts_trace_1[["storage_hostname", "disk_id", "disk_capacity", "disk_free_space", "percent_free", "disk_capacity_tb", "file_name"]].sort_values(["storage_hostname", "disk_id"])
ts_trace_1 = ts_trace_1.reset_index()
ts_trace_1 = ts_trace_1.drop("index", axis=1)
ts_trace_1 = ts_trace_1.sort_values(["storage_hostname", "disk_id"])
ts_trace_1 = ts_trace_1.set_index(keys=["storage_hostname", "disk_id"])
ts_trace_1 = ts_trace_1.groupby(["storage_hostname", "disk_id"]).agg(
    {
        "disk_capacity": "first", 
        "disk_free_space": "first",
        "percent_free": "first",
        "disk_capacity_tb": "first",
        "file_name": ', '.join
    }
)
ts_trace_1

In [ ]:
disks = disks.reset_index()
disks = disks.drop("index", axis=1)
disks = disks.set_index(keys=["storage_hostname", "disk_id"])
disks

In [ ]:
disks.update(ts_trace_1)
disks

In [ ]:
disks = pd.concat([disks,ts_trace_1]).drop_duplicates(['storage_hostname','disk_id'],keep='last')
disks = disks.reset_index()
disks = disks.drop("index", axis=1)
disks